name: Build and Deploy Code

on:   #trigger for cicd code to run; refer docs for all kinds of triggers like below
  push: # trigger on push requests 
    branches: #trigger push on branches of lists below
      - "main" #list all the other branches below if any needed triggering
  pull_request: #trigger on pull requests
    branches:
      - "main"

jobs: #jobs to run after the trigger
  job1:  #jobName
    env: #this env vars are accessible for this job only. mention env at 'on' level to be asscessible to all jobs
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: admin
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: vn387otDFJ3489FHhO87T76ir97I5DR5i7drow76rd5wer9q87G69T7IFUUO67Of865DO67rfri6RD976or67O
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRES_MINUTES: 30
    runs-on: ubuntu-latest #type of machine to run the job on
    steps: #named pipeline steps
      - name: pulling git repo #give name for the step
        uses: actions/checkout@v2  # use checkout from market place for git pull#command to be running; refer market place for common tasks prebuilt actions 
      - name: run a linux CLI command
        run: echo "heloo" #to run a linux command here coz we are on linux
      - name: Install python version 3.9
        uses: actions/setup-python@v2 #use setup-python from actions
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip #command to be run on our linuc machine
      - name: install all dependancies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: | #the pipe put here means that we can run multiple command as seen below
          pip install pytest
          pytest -s -x



  

      
